### ISSUE TITLE
1.35 support: Is this skin still maintained?

### ISSUE THREAD

**Issue by jdlrobson** [Dialexio/Jony#9]
hello!
I come here from https://www.mediawiki.org/wiki/Skin:Jony

I see that this skin doesn't currently work with the latest MediaWiki. I'm happy to push a patch to fix that but I wanted to check if it was still maintained first.

**Comment by Dialexio** [comment]
Hey, sorry for the radio silence. (I'm actually surprised somebody shared it on MediaWiki's site… you learn something new every day. 🤷)

I haven't really been doing a good job with maintaining Jony, due to a bad mixture of lack of time and lack of motivation. I'll be happy to merge in any pull requests to fix things up though.

**Comment by jdlrobson** [comment]
Sorry to hear about lack of motivation.  I've sent a patch which fixes up the skin so it's usable again and have kept backwards compatibility with older MediaWiki versions!

I'll take care of things mediawiki.org side. Our community is usually good at finding skins and sharing the ones they like so Id' wear it as a badge of honor that somebody shared it on mediawiki.org !

**Comment by jdlrobson** [comment]
It's now listed on https://skins.wmflabs.org/#/skin/jony :)
